### ISSUE TITLE
Workflows for tests

### ISSUE THREAD

**Issue by mkobos** [openaire/vipe#3]
We want to test tool’s ability to:
1. interpret Oozie workflow correctly,
2. extract information about data passed between between workflow nodes.

In order to do so, we need a set of various real-life-like Oozie workflows showing different use cases:
- subworkflows (e.g., workflow->subworkflow->subsubworkflow),
- fork, join,
- conditional execution paths,
- various types of nodes that we use: Java (standard and based on IIS’es Process class), MapReduce, Hadoop Streaming, Pig, distcp,
- nodes with multiple outputs (especially MapReduce),
- input and output paths defined through parameters (like in [metadataextraction workflow](https://github.com/openaire/iis/blob/master/iis-workflows/iis-workflows-metadataextraction/src/main/resources/eu/dnetlib/iis/workflows/metadataextraction/oozie_app/workflow.xml)),
  parameters and global definitions in Oozie file,
- IIS’es schema generators and by-passes,
- passing only the output directory parameter to subworkflow as the root directory that will contain many data stores produced by this subworkflow (as this is something that I saw in our workflows some time ago),
- maybe some other workflows showing other peculiarities?

These workflows will be used as a part of tool’s test suite.

**Comment by marekhorst** [comment]
Kind of `core-examples`?

**Comment by mkobos** [comment]
Ooh, that's good :) Sure.

**Comment by marekhorst** [comment]
I've just sent you whole package by email.

**Comment by mkobos** [comment]
Great. That's a huge package :) I'll take a look when I'm done with #4 since I need a code resulting from that task in order to incorporate the tests.

**Comment by marekhorst** [comment]
Just noticed `distcp` and `fs` `workflows.xml` files are swapped.

**Comment by mkobos** [comment]
Ok.

**Comment by mkobos** [comment]
Now I'm onto putting these workflows in the code and writing appropriate tests.

**Comment by mkobos** [comment]
I took the workflows that you sent me and integrated them as part of the tests in my local codebase.

Some of the workflows are a little too simple, can you extend them? Namely:
- bypass - add consumer
- conditional - add more cases, add consumer
- distcp - add consumer
- fork - add consumer
- fs - add consumer
- generatesschema - add some nodes actually using the generated schema
- global_section - add some nodes actually using the properties defined in the global section
- i-o_paths_parameters - add consumer
- java - add consumer
- pig  - add consumer

**Comment by marekhorst** [comment]
Why do we need consumers knowing those workflows are meant to be kind of templates, not to be fully functional and executable?

**Comment by mkobos** [comment]
To make the tests more real-life-like.

**Comment by marekhorst** [comment]
But we are still not looking into executable workflows, right? Can I push it somewhere in git?

**Comment by mkobos** [comment]
Correct. The easiest solution for me would be if you just sent me the files.

**Comment by marekhorst** [comment]
I've sent you another package. Although it will be much easier when pushing it through git - you would see all the changes and we could discuss it ;)

**Comment by mkobos** [comment]
Sure, but my concern was that I might inadvertently break something since I had a different branch open (the one that entered master in commit cc659ed0a4b5d781ba6571196d091c3bb9e1c929) and there might be a problem with merging. Maybe I was too careful.

**Comment by mkobos** [comment]
I finally managed to merge changes from different branches. Anyway, I created a new pull request corresponding to this issue, so we can move the discussion there: #13.
